# name: Translate GitHub Pull Requests

# on:
#   workflow_call:
#     secrets:
#       OPENAI_API_KEY:
#         required: true
#     inputs:
#       pr_number:
#         required: true
#         type: string
#       comment_id:
#         required: false
#         type: string

# jobs:
#   translate:
#     runs-on: ubuntu-latest
#     permissions:
#       pull-requests: write

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v3
#         with:
#           repository: rimoapp/bilingual-github

#       - name: Set Up Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: "3.8"

#       - name: Install Dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt

#       - name: Translate Pull Request
#         run: python src/actions/translate_prs.py
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
#           PR_NUMBER: ${{ inputs.pr_number }}
#           COMMENT_ID: ${{ inputs.comment_id }} 